spring.application.name=fitops
#database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/fitops}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.flyway.locations=classpath:db/migration
spring.flyway.default-schema=public
# SpringDoc OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=false
# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never